#!/bin/sh

# Get the current date in dd.mm.yy format
CURRENT_DATE=$(date "+%d.%m.%y")

# Get the commit message
COMMIT_MSG_FILE=$1
echo "$COMMIT_MSF_FILE"

# Check if the commit message starts with the current date
if ! echo "$COMMIT_MSG_FILE" | grep -q "^$CURRENT_DATE "; then
  echo "ERROR: Your commit message must start with the current date in dd.mm.yy format."
  exit  1
fi
