#!/bin/sh

# Get the current date in dd.mm.yy format
CURRENT_DATE=$(date "+%d.%m.%y")

# Get the commit message
COMMIT_MSG_FILE=$1
cat $COMMIT_MSG_FILE

# Check if the commit message starts with the current date
if [[ $COMMIT_MSG_FILE == $CURRENT_DATE\ * ]]; then
    echo "OK"
    exit  0 # Exit with success status code
elif [[ -z $COMMIT_MSG_FILE || $COMMIT_MSG_FILE == *[!0-9]* ]]; then
    echo "Msg should contain date"
    exit  0 # Exit with success status code
else
    echo "Invalid date format"
    exit  0 # Exit with success status code
fi